name: flutter_cupertino_date_picker
description: Flutter cupertino date picker. Display DatePicker in iOS style. Support both Android and iOS platform.

publish_to: "none"

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

flutter:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
